# Numpy Basics
What is NumPy?

NumPy is a Python library used for working with arrays.

It also has functions for working in domain of linear algebra, fourier transform, and matrices.
NumPy stands for Numerical Python.


In [70]:
import numpy as np

# Creating Arrays

In [71]:
a = np.array([1,2,3])
print(a)

[1 2 3]


In [72]:
b = np.array([[2,3,4],[5,6,7]])
print(b)

[[2 3 4]
 [5 6 7]]


# Inspecting your Array

In [73]:
b.ndim


2

In [74]:
b.shape

(2, 3)

In [75]:
b.dtype

dtype('int32')

In [76]:
b.size

6

In [77]:
b.size * b.itemsize

24

In [78]:
b.nbytes

24

In [79]:
a = np.array([[1,2,3,4,5],[6,7,8,9,0]])
print(a)

[[1 2 3 4 5]
 [6 7 8 9 0]]


In [80]:
# get a specific element(r,c)
a[1,2]

8

In [81]:
#get specific columun
a[:,0]

array([1, 6])

In [82]:
# get specific row
a[0,:]

array([1, 2, 3, 4, 5])

In [83]:
a[0,1:5:2]  # [start:end:step]

array([2, 4])

In [84]:
a[1,1] = 10
print(a)
a[:,2] = 5
print(a)

[[ 1  2  3  4  5]
 [ 6 10  8  9  0]]
[[ 1  2  5  4  5]
 [ 6 10  5  9  0]]


In [85]:
#3D example
b= np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [86]:
b[1,1,1]
b[0,1,0]

3

In [87]:
#replace
b[:,1,:] = [[9,9],[8,3]]

In [88]:
b

array([[[1, 2],
        [9, 9]],

       [[5, 6],
        [8, 3]]])

#  Initial Placeholers

In [89]:
# all 0s matrix
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [90]:
np.ones((4,2,3))

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

In [91]:
# any other number
np.full((3,3),99)

array([[99, 99, 99],
       [99, 99, 99],
       [99, 99, 99]])

In [92]:
#any other number(full_like)
np.full_like(a.shape,4)
np.full_like(a,5)

array([[5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5]])

In [93]:
# random decimnal number
np.random.rand(4,3)

array([[0.64080073, 0.59047488, 0.00305081],
       [0.81777988, 0.72256876, 0.29574432],
       [0.79139823, 0.10361111, 0.01857596],
       [0.04546385, 0.41876711, 0.50351305]])

In [94]:
# random integer number
np.random.randint(3,size=(2,3))  # 3 is exculsive

array([[1, 2, 2],
       [1, 1, 0]])

In [95]:
# the identity matrix
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [96]:
# repeat array
arr = np.array([[1,2,3]])
r = np.repeat(arr,3,  axis=0)
print(r)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [97]:
# problem
output = np.ones((5,5))
print(output)
z = np.zeros((3,3))
print(z)
z[1,1] = 9
print(z)
output[1:-1,1:-1] = z
print(output)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


#  Arithmetic Operations

In [98]:
c=np.array([2,4,6])
d=np.array([3,7,9])

In [99]:
g = c - d       #subtraction
print(g)

[-1 -3 -3]


In [100]:
np.subtract(c,d)  #subtraction

array([-1, -3, -3])

In [101]:
c + d            # addition

array([ 5, 11, 15])

In [102]:
np.add(c,d)    #addition

array([ 5, 11, 15])

In [103]:
c / d            #division

array([0.66666667, 0.57142857, 0.66666667])

In [104]:
np.divide(c,d)     # division

array([0.66666667, 0.57142857, 0.66666667])

In [105]:
c * d               #multiplication

array([ 6, 28, 54])

In [106]:
np.multiply(c,d)       #multiplication

array([ 6, 28, 54])

In [107]:
np.exp(c)            #exponentiation

array([  7.3890561 ,  54.59815003, 403.42879349])

In [108]:
np.sqrt(c)          #square root

array([1.41421356, 2.        , 2.44948974])

In [109]:
np.sin(d)            # print sines of an array

array([0.14112001, 0.6569866 , 0.41211849])

In [110]:
np.cos(d)            # element-wise cosine

array([-0.9899925 ,  0.75390225, -0.91113026])

In [111]:
np.log(c)            # element-wise natural logarithm

array([0.69314718, 1.38629436, 1.79175947])

In [112]:
c.dot(d)              # dot product

88

#  Aggregate Functions

In [113]:
a.sum()    # array-wise sum

47

In [114]:
a.min()     # array-wise minimum value

0

In [115]:
b.max(axis=0)   #maximum value of an array row

array([[5, 6],
       [9, 9]])

In [116]:
b.cumsum(axis=1)  #cumlative sum of the elemnts

array([[[ 1,  2],
        [10, 11]],

       [[ 5,  6],
        [13,  9]]], dtype=int32)

In [117]:
a.mean()  #mean

4.7

In [118]:
np.median(b)  #median

5.5

In [119]:
np.corrcoef(a)      #corelation coefficient

array([[ 1.        , -0.52433452],
       [-0.52433452,  1.        ]])

In [120]:
np.std(b)            # standard deviation

2.9553976043842223

# Sorting Arrays

In [121]:
a.sort()      # sort an array

In [122]:
c.sort(axis=0)   # sort the element of an array's axis

# Transposing Array

In [123]:
i = np.transpose(b)

In [124]:
i.T

array([[[1, 2],
        [9, 9]],

       [[5, 6],
        [8, 3]]])

#  Changing Array Shape

In [125]:
b.ravel()     #permute array dimensions

array([1, 2, 9, 9, 5, 6, 8, 3])

In [126]:
d.reshape(3,-2)

array([[3],
       [7],
       [9]])

#  Thank You!